# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef4ed3c244eb57d223a52f776ed9f6fd"
name = "oshi-app"
handle = "oshi-app"
application_url = "https://updates-repeated-van-licence.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sajid-development-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_fulfillments,read_locations,read_merchant_managed_fulfillment_orders,read_order_edits,read_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_locations,write_merchant_managed_fulfillment_orders,write_order_edits,write_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://updates-repeated-van-licence.trycloudflare.com/auth/callback",
  "https://updates-repeated-van-licence.trycloudflare.com/auth/shopify/callback",
  "https://updates-repeated-van-licence.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
