# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dbde4200a667f99572d4d41d28ca107c"
name = "Oshi App"
handle = "oshi-app-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-0e519633.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
